language: node_js
node_js:
  - 4
  - 5
  - 6
  - node
before_script:
  - npm install
env:
  global:
    - LOGGER_INFO_PATH=/var/log/eventoLInfo.log
    - LOGGER_ERROR_PATH=/var/log/eventoLError.log
  - NODE_ENV=develop
  - NODE_ENV=production
script: sh unit.sh
