language: node_js
node_js:
  - 4
  - 5
  - 6
  - node
before_script:
  - npm install
env:
  global:
    - LOGGER_INFO_PATH=/var/log/eventoLInfo.log
    - LOGGER_ERROR_PATH=/var/log/eventoLError.log
  matrix:
    - NODE_ENV=develop
script: sh unit.sh
addons:
  code_climate:
    repo_token: 57bb0fc3f32fdc13a2004e7c
