version: '2'
services:
  eventol-api:
    image: fedeg/eventol-api:latest
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=develop
      - LOGGER_INFO_PATH=/var/log/eventoLInfo.log
      - LOGGER_ERROR_PATH=/var/log/eventoLError.log
      - DOCS_IN_PAGE=10
      - DEFAULT_PAGE=1
      - DISTANCE=1000
      - PORT=3000
      - HOST=0.0.0.0
      - API_URL=http://localhost:3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=eventoL
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes_from:
      - mongo-data
  mongo-data:
    image: fedeg/eventol-mongo-data
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
